### ISSUE TITLE
Blank action button in components in Ember 1.13.5

### ISSUE THREAD

**Issue by Eric-Guo** [truenorth/wge-examples#1]
I try to port your PPT wge-examples to newest ember.js 1.13.5, but found blank action button.

But seems every thing is all right (maybe I still too new to ember.js), so can you give some hint?

https://github.com/Eric-Guo/ember-examples-with-cli/compare/wge-examples

![blank_action_button](https://cloud.githubusercontent.com/assets/1131536/8770868/5d5a1a1e-2eeb-11e5-88fd-8e2e293e9133.png)

**Comment by mike-north** [comment]
The approach I took to capture a block of handlebars and project it into the parent component has been removed in ember 1.13. Hopefully one of the upcoming component RFCs will offer a new (and more sustainable) path forward

**Comment by Eric-Guo** [comment]
@truenorth Thank you kindly hints, the code you shared show so many trick and your speech is also best in Wicked Good Ember 2015 in my options.

**Comment by mike-north** [comment]
thanks :)
